from reportlab.lib.pagesizes import A4
from reportlab.pdfgen import canvas
from datetime import datetime
import os


def generate_scorecard_pdf(data, user_email):

    folder = "app/generated_scorecards"
    os.makedirs(folder, exist_ok=True)

    filename = f"scorecard_{datetime.now().strftime('%Y%m%d%H%M%S')}.pdf"
    path = os.path.join(folder, filename)

    c = canvas.Canvas(path, pagesize=A4)
    width, height = A4

    c.setFont("Helvetica-Bold", 22)
    c.drawString(50, height - 60, "TalentIQ Interview Scorecard")

    c.setFont("Helvetica", 11)
    c.drawString(50, height - 90, f"Candidate: {user_email}")
    c.drawString(50, height - 110, f"Generated On: {datetime.now().strftime('%d-%m-%Y %H:%M')}")

    y = height - 160

    c.setFont("Helvetica-Bold", 16)
    c.drawString(50, y, "Scores")
    y -= 35

    c.setFont("Helvetica", 13)
    c.drawString(70, y, f"Final Score: {data.get('final_score', 0)}/10")
    y -= 25
    c.drawString(70, y, f"Technical Accuracy: {data.get('technical_score', 0)}/10")
    y -= 25
    c.drawString(70, y, f"Communication Score: {data.get('communication_score', 0)}/10")
    y -= 25
    c.drawString(70, y, f"Confidence Rating: {data.get('confidence_score', 0)}/10")

    y -= 45

    def write_section(title, items):
        nonlocal y

        c.setFont("Helvetica-Bold", 15)
        c.drawString(50, y, title)
        y -= 25

        c.setFont("Helvetica", 12)

        if not items:
            items = ["No data available"]

        for item in items:
            c.drawString(70, y, f"- {item}")
            y -= 22

    write_section("Strengths", data.get("strengths", []))
    y -= 10
    write_section("Weaknesses", data.get("weaknesses", []))
    y -= 10
    write_section("Improvement Suggestions", data.get("suggestions", []))

    c.setFont("Helvetica-Oblique", 10)
    c.drawString(50, 40, "Generated by TalentIQ - AI Career Intelligence Platform")

    c.save()

    return path